export enum carCategory{
    SEDAN = 'SEDAN',
    SUV = 'SUV',
    COUPE = 'COUPE',
    CONVERTIBLE = 'CONVERTIBLE',
    HATCHBACK = 'HATCHBACK',
    WAGON = 'WAGON',
    PICKUP = 'PICKUP',
    MINIVAN = 'MINIVAN',
    SPORTS_CAR = 'SPORTS_CAR',
    ELECTRIC = 'ELECTRIC',
    HYBRID = 'HYBRID',
    DIESEL = 'DIESEL',
    LUXURY = 'LUXURY',
    OFF_ROAD = 'OFF_ROAD',
    COMMERCIAL = 'COMMERCIAL'
}